# Generated by Django 4.2.9 on 2026-04-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Login email for the organisation admin', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Hashed password', max_length=255),
        ),
        migrations.CreateModel(
            name='OrgToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='timetable_app.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
