# Generated by Django 4.2.9 on 2026-06-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0006_remove_admin_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobhistory',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Job History', 'verbose_name_plural': 'Job Histories'},
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Latest available end time on this day (optional — worker sets upper bound)', null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(help_text='Earliest available start time on this day'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Org admin that added this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employments', to='timetable_app.organisation'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='is_current',
            field=models.BooleanField(default=True, help_text='True while the user is actively employed at this org'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Datetime when the user joined this organisation'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='left_at',
            field=models.DateTimeField(blank=True, help_text='Datetime when the user left this organisation (null if still current)', null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='work_type',
            field=models.CharField(blank=True, default='', help_text='Snapshot of work_type at the time of joining', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='country_code',
            field=models.CharField(blank=True, default='', help_text='Dial code, e.g. +49', max_length=6),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='owner_name',
            field=models.CharField(blank=True, default='', help_text='Full name of the organisation owner / admin', max_length=150),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Bcrypt-hashed password — never store plain text here', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number with country code, e.g. +4917612345678', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='shop_close',
            field=models.TimeField(default='20:00', help_text='Daily closing time (HH:MM) — no shift may end after this'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='shop_open',
            field=models.TimeField(default='08:00', help_text='Daily opening time (HH:MM) — no shift may start before this'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='hours',
            field=models.DecimalField(decimal_places=2, help_text='Shift duration in hours — auto-calculated on save', max_digits=4),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to='timetable_app.organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Globally unique email address for this person', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Currently active organisation. Null = not employed anywhere.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='timetable_app.organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Globally unique phone number for this person', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Shown once on creation to the org admin, then cleared', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('WORKER', 'Worker')], default='WORKER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('MINIJOB', 'Mini Job')], help_text='Employment type — determines weekly hour limit', max_length=20, null=True),
        ),
    ]
